#on:
#  push:
#    branches:
#    - master
on:
  pull_request:
    branches:
    - master
    
jobs:
  deploy:
    name: Deploy GitHub pages
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build static site
      shell: pwsh
      run: .\Tools\BuildStatic.ps1 $pwd.path
    - name: Deploy to GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ../output
        branch: master
    
    
